
[font]
size = 16.0

[font.bold]
family = "JetBrains Mono"

[font.italic]
family = "JetBrains Mono"

[font.normal]
family = "JetBrains Mono"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
opacity = 0.5

[window.padding]
x = 15
y = 15

[general]
live_config_reload = true
