#! /bin/bash
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
export ANDROID_HOME=/home/tai/opt/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:/home/tai/opt/android-studio/bin
export _JAVA_AWT_WM_NONREPARENTING=1
export GTK_THEME=Adwaita:dark
export VISUAL=vim
export EDITOR="$VISUAL"
source ~/.cache/wal/colors-tty.sh

sxhkd &

setxkbmap -layout br

bspc monitor -d Home Dev Support Terminal Music Chat Sys Info Random
bspc config automatic_scheme alternate
bspc config split_ratio 0.5
bspc config initial_polarity second_child
bspc config external_rules_command ${HOME}/scripts/emulator-launch.sh

#lauching polywal
wal -f ~/.cache/wal/colors
. "${HOME}/.cache/wal/colors.sh"

bspc config border_width         0
bspc config window_gap          12
#bspc config focused_border_color "$color15"
#bspc config focused_border_color \#000000
bspc config normal_border_color "$color10"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config bottom_monocle_padding 0
bspc config gapless_monocle      true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr

#launching xorg compositor
pkill picom
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom &

feh --bg-fill ~/papers/`cat ~/.background-image`

#configure touchpad
#~/scripts/configure_touchpad.sh

#numlock on
numlockx &

#map caps-lock to esc	
~/scripts/caps-esc.sh

xmodmap -e 'keycode 77 = grave'

xmodmap -e 'keycode 9 = apostrophe quotedbl apostrophe quotedbl'

#handle headphone mic
#~/scripts/handle-mic.sh &

#update clock 
#~/scripts/sincro-clock.sh &

#watch monitors
#node ~/scripts/handle-monitors.js &

#watch devices
#~/scripts/watch-devices.sh &

#start polybar
~/.config/polybar/launch.sh &

#launch redshift
#pkill redshift
#while pgrep -u $UID -x redshift >/dev/null; do sleep 1; done
#redshift &


wmname LG3D &

bspc rule -a android-studio state=floating border=off follow=on
bspc rule -a "Realm Studio" state=floating center=on follow=on
bspc rule -a "realm studio" state=floating center=on follow=on
bspc rule -a Alacritty state=floating center=on follow=on
bspc rule -a Nemo state=floating center=on follow=on
bspc rule -a feh state=floating 

#setup startpage server
node ~/projetos/tqs/main.js &
