#! /bin/bash
sxhkd &

setxkbmap -layout br

m=($(xrandr -q | grep " connected" | cut -d ' ' -f1))
if [[ "${#m[@]}" == "2" ]];then
	~/scripts/move-to-hdmi
else
	~/scripts/move-to-edp
fi
. "${HOME}/.cache/wal/colors.sh"
bspc config border_width         1
bspc config window_gap          12
#bspc config focused_border_color "$color15"
bspc config focused_border_color \#000000
bspc config normal_border_color "$color10"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config bottom_monocle_padding 0
bspc config gapless_monocle      true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr

#launching xorg compositor
pkill picom
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom &

#lauching polywal
wal -R
feh --bg-fill ~/papers/`cat ~/.background-image`

#configure touchpad
~/scripts/configure_touchpad.sh

#numlock on
numlockx &

#map caps-lock to esc	
~/scripts/caps-esc.sh

#handle headphone mic
~/scripts/handle-mic.sh &

#update clock 
~/scripts/sincro-clock.sh &

#watch monitors
node ~/scripts/handle-monitors.js &

#watch devices
~/scripts/watch-devices.sh &

#start polybar
~/.config/polybar/launch.sh &

#launch redshift
pkill redshift
while pgrep -u $UID -x redshift >/dev/null; do sleep 1; done
redshift &

#setup startpage server
node ~/projetos/tqs/main.js

